name: CI workflow

on:
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  test-and-lighthouse:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run jest test
        run: npm run test

      - name: Build project for lighthouse checking
        run: npm run build

      - name: Run lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: "./lighthouserc.json"
